---
# tasks file for wordpress
- name: download wordpress
  get_url: 
    url: 'http://wordpress.org/latest.tar.gz'
    dest: '/tmp/latest.tar.gz'

- name: unarchive wordpress
  unarchive: 
    src: /tmp/latest.tar.gz
    dest: /tmp/
    remote_src: yes
    owner: apache
    group: apache

- name: install rsync required by synchronize
  yum:
    name: rsync
    state: latest

# copy does not yet support recursive directory
- synchronize:
    src: /tmp/wordpress/
    dest: /var/www/html/
    owner: apache
    group: apache
  delegate_to: "{{ inventory_hostname }}"

- name: copy template file to webserver
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wp-config.php
    owner: apache
    group: apache